### PR TITLE
Fix build with Qt 5.15+

### PR DESCRIPTION
**Pull request by felixonmars**
```
/build/hedgewars/src/hedgewars-src-1.0.0/QTfrontend/ui/page/pagegamestats.cpp: In member function ‘void PageGameStats::renderStats()’:
/build/hedgewars/src/hedgewars-src-1.0.0/QTfrontend/ui/page/pagegamestats.cpp:222:26: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
  222 |             QPainterPath path;
      |                          ^~~~
```

### CODE REVIEW

**Comment by Wuzzy2** [comment]
Thanks! And committed:

http://hg.hedgewars.org/hedgewars/rev/c259073a8052

This issue can be closed now.
